## Задание 5.1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [8]:
import numpy as np

a = np.arange(12, 24)
print(a)
a.shape

[12 13 14 15 16 17 18 19 20 21 22 23]


(12,)

## Задание 5.2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [18]:
a1 = np.reshape(a, (1,12))
print(a1.shape)
print(a1)

(1, 12)
[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [19]:
a2 = np.reshape(a, (2,6))
print(a2.shape)
print(a2)

(2, 6)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [21]:
a3 = np.reshape(a, (3,4))
print(a3.shape)
print(a3)

(3, 4)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [24]:
a4 = np.reshape(a, (4,3))
print(a4.shape)
print(a4)

(4, 3)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [27]:
a5 = np.reshape(a, (6,2))
print(a5.shape)
print(a5)

(6, 2)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


## Задание 5.3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
(в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [28]:
a1 = np.reshape(a, (1,-1))
print(a1.shape)
print(a1)

(1, 12)
[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [29]:
a2 = np.reshape(a, (2,-1))
print(a2.shape)
print(a2)

(2, 6)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [30]:
a3 = np.reshape(a, (3,-1))
print(a3.shape)
print(a3)

(3, 4)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [31]:
a4 = np.reshape(a, (-1,3))
print(a4.shape)
print(a4)

(4, 3)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [32]:
a5 = np.reshape(a, (-1,2))
print(a5.shape)
print(a5)

(6, 2)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


## Задание 5.4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет, нельзя

## Задание 5.5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким
же атрибутом size, как и исходный массив.


In [45]:
r = np.random.randn(3, 4)
r

array([[ 0.07922471, -1.55747377, -0.31504611, -1.07093555],
       [-1.86148746, -0.00988257,  1.24551317, -0.23685805],
       [ 0.60878434,  0.44092305,  0.51321157,  1.31776204]])

In [46]:
print(r.mean())
print(r.std())

-0.0705220508719782
0.9685053023172168


In [67]:
d1 = r.flatten()
print(d1)
print(d1.shape)

[ 0.07922471 -1.55747377 -0.31504611 -1.07093555 -1.86148746 -0.00988257
  1.24551317 -0.23685805  0.60878434  0.44092305  0.51321157  1.31776204]
(12,)


## Задание 5.6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [78]:
a = np.arange(20,0,-2)
print(a)


[20 18 16 14 12 10  8  6  4  2]


## Задание 5.7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?



In [81]:
b = np.arange(20,1,-2).reshape(1,10)
print(b)
# массив a - одномерный, массив b - двумерный

[[20 18 16 14 12 10  8  6  4  2]]
